theme: jekyll-theme-primer
title: SpotifYou
description: Generate YOUR Spotify playlist
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
theme: just-the-docs
search_enabled: true
exclude: ["*.json", "*.csv", "*.ipynb", "*.pdf", "papers/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]
aux_links:
  "SpotifYou on GitHub":
      - "//github.com/gzgracez/CS-109A-Final-Project"